Repository CNU-Capstone-Design/Capstone-BackEnd, pull requests merged in 2024-05, with the labels that each got.

#1 feat: test file add
  .gitignore
  ai-server/lambda.ipynb
  ai-server/sagemaker-notebook.ipynb
  spring-server/aistyling/.gitignore
  spring-server/aistyling/build.gradle
  spring-server/aistyling/gradle/wrapper/gradle-wrapper.jar
  spring-server/aistyling/gradle/wrapper/gradle-wrapper.properties
  spring-server/aistyling/gradlew
  spring-server/aistyling/gradlew.bat
  spring-server/aistyling/settings.gradle
  spring-server/aistyling/src/main/java/com/clothz/aistyling/AistylingApplication.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/api/ApiControllerAdvice.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/api/ApiResponse.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/api/controller/UserController.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/api/controller/dto/request/UserCreateRequest.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/api/service/user/UserService.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/api/service/user/response/UserResponse.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/domain/BaseEntity.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/domain/user/User.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/domain/user/UserRepository.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/domain/user/constant/UserRole.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/global/config/JpaAuditingConfig.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/global/jwt/JwtProvider.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/global/jwt/PasswordUtil.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/global/jwt/dto/LoginResponse.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/global/jwt/filter/JwtAuthenticationFilter.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/global/jwt/handler/LoginFailureHandler.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/global/jwt/handler/LoginSuccessHandler.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/global/jwt/service/LoginService.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/global/jwt/userInfo/CustomJsonUsernamePasswordAuthenticationFilter.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/global/jwt/userInfo/CustomUserDetails.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/global/security/SpringSecurityConfig.java
  spring-server/aistyling/src/main/resources/application-local.yml
  spring-server/aistyling/src/main/resources/application.yml
  spring-server/aistyling/src/test/java/com/clothz/aistyling/AistylingApplicationTests.java
  spring-server/aistyling/src/test/java/com/clothz/aistyling/api/controller/UserControllerTest.java
Labels: Priority: High, Status: Todo

#5 로그인, 회원가입, 이미지 업로드 기능 개발
  spring-server/aistyling/build.gradle
  spring-server/aistyling/src/main/java/com/clothz/aistyling/api/controller/UserController.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/api/controller/user/UserController.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/api/controller/user/request/UserCreateRequest.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/api/service/user/UserService.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/api/service/user/response/UserImagesResponse.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/api/service/user/response/UserInfoResponse.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/api/service/user/response/UserResponse.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/api/service/user/response/UserSingUpResponse.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/domain/user/User.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/global/s3/AwsCredentialsProvider.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/global/s3/S3Service.java
  spring-server/aistyling/src/main/resources/application-cloud.yml
  spring-server/aistyling/src/main/resources/application.yml
  spring-server/aistyling/src/test/java/com/clothz/aistyling/api/controller/UserControllerTest.java
  spring-server/aistyling/src/test/java/com/clothz/aistyling/api/service/user/UserServiceTest.java
  spring-server/aistyling/src/test/java/com/clothz/aistyling/domain/user/UserRepositoryTest.java
Labels: Priority: High, Type: Feature, Type: Style, Type: Test

#16 회원 정보 수정 기능 관련 리팩토링
  spring-server/aistyling/src/main/java/com/clothz/aistyling/api/service/home/HomeService.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/api/service/home/response/HomeResponse.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/api/service/styling/StylingService.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/api/service/styling/response/StylingExampleResponse.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/api/service/user/UserService.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/api/service/user/response/UserUpdateResponse.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/domain/user/User.java
  spring-server/aistyling/src/test/java/com/clothz/aistyling/api/controller/home/HomeControllerTest.java
  spring-server/aistyling/src/test/java/com/clothz/aistyling/api/controller/styling/StylingControllerTest.java
  spring-server/aistyling/src/test/java/com/clothz/aistyling/api/service/home/HomeServiceTest.java
  spring-server/aistyling/src/test/java/com/clothz/aistyling/api/service/styling/StylingServiceTest.java
  spring-server/aistyling/src/test/java/com/clothz/aistyling/api/service/user/UserServiceTest.java
Labels: Priority: Medium, Type: Refactoring

#20 Feat#7
  spring-server/aistyling/src/main/java/com/clothz/aistyling/api/ApiResponse.java
  spring-server/aistyling/src/main/java/com/clothz/aistyling/api/controller/user/UserController.java
  spring-server/aistyling/src/test/java/com/clothz/aistyling/api/controller/user/UserControllerTest.java
Labels: Priority: Medium

#23 chore: Docker AWS 환경 변수 설정
  .github/workflows/gradle.yml
  Dockerfile
  src/main/resources/application-prod.yml
Labels: Priority: High, Type: Configuration

#25 chore: Swagger 설정
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/com/clothz/aistyling/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: Priority: High, Type: Configuration

#27 에러 타입 정의
  src/main/java/com/clothz/aistyling/api/ApiControllerAdvice.java
  src/main/java/com/clothz/aistyling/api/controller/home/HomeController.java
  src/main/java/com/clothz/aistyling/api/controller/styling/StylingController.java
  src/main/java/com/clothz/aistyling/api/controller/user/UserController.java
  src/main/java/com/clothz/aistyling/api/service/home/HomeService.java
  src/main/java/com/clothz/aistyling/global/api/ApiControllerAdvice.java
  src/main/java/com/clothz/aistyling/global/api/ApiResponse.java
  src/main/java/com/clothz/aistyling/global/error/Exception400.java
  src/main/java/com/clothz/aistyling/global/error/Exception401.java
  src/main/java/com/clothz/aistyling/global/error/Exception403.java
  src/main/java/com/clothz/aistyling/global/error/Exception404.java
  src/main/java/com/clothz/aistyling/global/error/Exception500.java
  src/main/java/com/clothz/aistyling/global/jwt/handler/LoginFailureHandler.java
  src/main/java/com/clothz/aistyling/global/jwt/handler/LoginSuccessHandler.java
Labels: Priority: High, Type: Configuration, Type: Feature, Type: Style

#28 ErrorCode Enum타입정의하고, Exception400~Exception500까지 수정
  src/main/java/com/clothz/aistyling/global/error/ErrorCode.java
  src/main/java/com/clothz/aistyling/global/error/Exception400.java
  src/main/java/com/clothz/aistyling/global/error/Exception401.java
  src/main/java/com/clothz/aistyling/global/error/Exception403.java
  src/main/java/com/clothz/aistyling/global/error/Exception404.java
  src/main/java/com/clothz/aistyling/global/error/Exception500.java
Labels: Priority: Medium

#31 코드 리팩토링
  src/main/java/com/clothz/aistyling/api/controller/user/UserController.java
  src/main/java/com/clothz/aistyling/api/service/styling/StylingService.java
  src/main/resources/application-test.yml
  src/test/java/com/clothz/aistyling/api/controller/home/HomeControllerTest.java
  src/test/java/com/clothz/aistyling/api/controller/user/UserControllerTest.java
  src/test/java/com/clothz/aistyling/api/service/home/HomeServiceTest.java
  src/test/java/com/clothz/aistyling/api/service/styling/StylingServiceTest.java
  src/test/java/com/clothz/aistyling/api/service/user/UserServiceTest.java
Labels: Priority: Medium, Type: Refactoring

#34 회원 가입 시 사진 업로드 기능 추가
  src/main/java/com/clothz/aistyling/api/controller/user/UserController.java
  src/main/java/com/clothz/aistyling/api/service/user/UserService.java
  src/test/java/com/clothz/aistyling/api/controller/user/UserControllerTest.java
  src/test/java/com/clothz/aistyling/api/service/user/UserServiceTest.java
  src/test/resources/application.yml
Labels: Priority: Medium, Type: Feature

#35 스타일링 관련 기능 리팩토링
  src/main/java/com/clothz/aistyling/AistylingApplication.java
  src/main/java/com/clothz/aistyling/api/controller/styling/StylingController.java
  src/main/java/com/clothz/aistyling/api/controller/styling/request/StylingWordsRequest.java
  src/main/java/com/clothz/aistyling/api/service/styling/StylingService.java
  src/main/java/com/clothz/aistyling/api/service/user/response/UserUpdateResponse.java
Labels: Priority: High, Type: Refactoring
